//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASMXUsecase.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.FlightCalculatorSoap")]
    public interface FlightCalculatorSoap {
        
        // CODEGEN: Generating message contract since element name GetFligtsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFligts", ReplyAction="*")]
        ASMXUsecase.ServiceReference1.GetFligtsResponse GetFligts(ASMXUsecase.ServiceReference1.GetFligtsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFligts", ReplyAction="*")]
        System.Threading.Tasks.Task<ASMXUsecase.ServiceReference1.GetFligtsResponse> GetFligtsAsync(ASMXUsecase.ServiceReference1.GetFligtsRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateNewFlight", ReplyAction="*")]
        ASMXUsecase.ServiceReference1.CreateNewFlightResponse CreateNewFlight(ASMXUsecase.ServiceReference1.CreateNewFlightRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateNewFlight", ReplyAction="*")]
        System.Threading.Tasks.Task<ASMXUsecase.ServiceReference1.CreateNewFlightResponse> CreateNewFlightAsync(ASMXUsecase.ServiceReference1.CreateNewFlightRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFligtsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFligts", Namespace="http://tempuri.org/", Order=0)]
        public ASMXUsecase.ServiceReference1.GetFligtsRequestBody Body;
        
        public GetFligtsRequest() {
        }
        
        public GetFligtsRequest(ASMXUsecase.ServiceReference1.GetFligtsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetFligtsRequestBody {
        
        public GetFligtsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFligtsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFligtsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ASMXUsecase.ServiceReference1.GetFligtsResponseBody Body;
        
        public GetFligtsResponse() {
        }
        
        public GetFligtsResponse(ASMXUsecase.ServiceReference1.GetFligtsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFligtsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ASMXUsecase.ServiceReference1.ArrayOfString GetFligtsResult;
        
        public GetFligtsResponseBody() {
        }
        
        public GetFligtsResponseBody(ASMXUsecase.ServiceReference1.ArrayOfString GetFligtsResult) {
            this.GetFligtsResult = GetFligtsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateNewFlightRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateNewFlight", Namespace="http://tempuri.org/", Order=0)]
        public ASMXUsecase.ServiceReference1.CreateNewFlightRequestBody Body;
        
        public CreateNewFlightRequest() {
        }
        
        public CreateNewFlightRequest(ASMXUsecase.ServiceReference1.CreateNewFlightRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateNewFlightRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string to;
        
        public CreateNewFlightRequestBody() {
        }
        
        public CreateNewFlightRequestBody(string name, string from, string to) {
            this.name = name;
            this.from = from;
            this.to = to;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateNewFlightResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateNewFlightResponse", Namespace="http://tempuri.org/", Order=0)]
        public ASMXUsecase.ServiceReference1.CreateNewFlightResponseBody Body;
        
        public CreateNewFlightResponse() {
        }
        
        public CreateNewFlightResponse(ASMXUsecase.ServiceReference1.CreateNewFlightResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateNewFlightResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateNewFlightResult;
        
        public CreateNewFlightResponseBody() {
        }
        
        public CreateNewFlightResponseBody(bool CreateNewFlightResult) {
            this.CreateNewFlightResult = CreateNewFlightResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FlightCalculatorSoapChannel : ASMXUsecase.ServiceReference1.FlightCalculatorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FlightCalculatorSoapClient : System.ServiceModel.ClientBase<ASMXUsecase.ServiceReference1.FlightCalculatorSoap>, ASMXUsecase.ServiceReference1.FlightCalculatorSoap {
        
        public FlightCalculatorSoapClient() {
        }
        
        public FlightCalculatorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FlightCalculatorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlightCalculatorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlightCalculatorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ASMXUsecase.ServiceReference1.GetFligtsResponse ASMXUsecase.ServiceReference1.FlightCalculatorSoap.GetFligts(ASMXUsecase.ServiceReference1.GetFligtsRequest request) {
            return base.Channel.GetFligts(request);
        }
        
        public ASMXUsecase.ServiceReference1.ArrayOfString GetFligts() {
            ASMXUsecase.ServiceReference1.GetFligtsRequest inValue = new ASMXUsecase.ServiceReference1.GetFligtsRequest();
            inValue.Body = new ASMXUsecase.ServiceReference1.GetFligtsRequestBody();
            ASMXUsecase.ServiceReference1.GetFligtsResponse retVal = ((ASMXUsecase.ServiceReference1.FlightCalculatorSoap)(this)).GetFligts(inValue);
            return retVal.Body.GetFligtsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ASMXUsecase.ServiceReference1.GetFligtsResponse> ASMXUsecase.ServiceReference1.FlightCalculatorSoap.GetFligtsAsync(ASMXUsecase.ServiceReference1.GetFligtsRequest request) {
            return base.Channel.GetFligtsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ASMXUsecase.ServiceReference1.GetFligtsResponse> GetFligtsAsync() {
            ASMXUsecase.ServiceReference1.GetFligtsRequest inValue = new ASMXUsecase.ServiceReference1.GetFligtsRequest();
            inValue.Body = new ASMXUsecase.ServiceReference1.GetFligtsRequestBody();
            return ((ASMXUsecase.ServiceReference1.FlightCalculatorSoap)(this)).GetFligtsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ASMXUsecase.ServiceReference1.CreateNewFlightResponse ASMXUsecase.ServiceReference1.FlightCalculatorSoap.CreateNewFlight(ASMXUsecase.ServiceReference1.CreateNewFlightRequest request) {
            return base.Channel.CreateNewFlight(request);
        }
        
        public bool CreateNewFlight(string name, string from, string to) {
            ASMXUsecase.ServiceReference1.CreateNewFlightRequest inValue = new ASMXUsecase.ServiceReference1.CreateNewFlightRequest();
            inValue.Body = new ASMXUsecase.ServiceReference1.CreateNewFlightRequestBody();
            inValue.Body.name = name;
            inValue.Body.from = from;
            inValue.Body.to = to;
            ASMXUsecase.ServiceReference1.CreateNewFlightResponse retVal = ((ASMXUsecase.ServiceReference1.FlightCalculatorSoap)(this)).CreateNewFlight(inValue);
            return retVal.Body.CreateNewFlightResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ASMXUsecase.ServiceReference1.CreateNewFlightResponse> ASMXUsecase.ServiceReference1.FlightCalculatorSoap.CreateNewFlightAsync(ASMXUsecase.ServiceReference1.CreateNewFlightRequest request) {
            return base.Channel.CreateNewFlightAsync(request);
        }
        
        public System.Threading.Tasks.Task<ASMXUsecase.ServiceReference1.CreateNewFlightResponse> CreateNewFlightAsync(string name, string from, string to) {
            ASMXUsecase.ServiceReference1.CreateNewFlightRequest inValue = new ASMXUsecase.ServiceReference1.CreateNewFlightRequest();
            inValue.Body = new ASMXUsecase.ServiceReference1.CreateNewFlightRequestBody();
            inValue.Body.name = name;
            inValue.Body.from = from;
            inValue.Body.to = to;
            return ((ASMXUsecase.ServiceReference1.FlightCalculatorSoap)(this)).CreateNewFlightAsync(inValue);
        }
    }
}
