//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.FlightNamespace {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FlightNamespace.FlightCalculatorSoap")]
    public interface FlightCalculatorSoap {
        
        // CODEGEN: Generating message contract since element name GetFligtsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFligts", ReplyAction="*")]
        WebApplication1.FlightNamespace.GetFligtsResponse GetFligts(WebApplication1.FlightNamespace.GetFligtsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFligts", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.FlightNamespace.GetFligtsResponse> GetFligtsAsync(WebApplication1.FlightNamespace.GetFligtsRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateNewFlight", ReplyAction="*")]
        WebApplication1.FlightNamespace.CreateNewFlightResponse CreateNewFlight(WebApplication1.FlightNamespace.CreateNewFlightRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateNewFlight", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.FlightNamespace.CreateNewFlightResponse> CreateNewFlightAsync(WebApplication1.FlightNamespace.CreateNewFlightRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFligtsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFligts", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.FlightNamespace.GetFligtsRequestBody Body;
        
        public GetFligtsRequest() {
        }
        
        public GetFligtsRequest(WebApplication1.FlightNamespace.GetFligtsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetFligtsRequestBody {
        
        public GetFligtsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFligtsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFligtsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.FlightNamespace.GetFligtsResponseBody Body;
        
        public GetFligtsResponse() {
        }
        
        public GetFligtsResponse(WebApplication1.FlightNamespace.GetFligtsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFligtsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication1.FlightNamespace.ArrayOfString GetFligtsResult;
        
        public GetFligtsResponseBody() {
        }
        
        public GetFligtsResponseBody(WebApplication1.FlightNamespace.ArrayOfString GetFligtsResult) {
            this.GetFligtsResult = GetFligtsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateNewFlightRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateNewFlight", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.FlightNamespace.CreateNewFlightRequestBody Body;
        
        public CreateNewFlightRequest() {
        }
        
        public CreateNewFlightRequest(WebApplication1.FlightNamespace.CreateNewFlightRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateNewFlightRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string to;
        
        public CreateNewFlightRequestBody() {
        }
        
        public CreateNewFlightRequestBody(string name, string from, string to) {
            this.name = name;
            this.from = from;
            this.to = to;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateNewFlightResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateNewFlightResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.FlightNamespace.CreateNewFlightResponseBody Body;
        
        public CreateNewFlightResponse() {
        }
        
        public CreateNewFlightResponse(WebApplication1.FlightNamespace.CreateNewFlightResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateNewFlightResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateNewFlightResult;
        
        public CreateNewFlightResponseBody() {
        }
        
        public CreateNewFlightResponseBody(bool CreateNewFlightResult) {
            this.CreateNewFlightResult = CreateNewFlightResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FlightCalculatorSoapChannel : WebApplication1.FlightNamespace.FlightCalculatorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FlightCalculatorSoapClient : System.ServiceModel.ClientBase<WebApplication1.FlightNamespace.FlightCalculatorSoap>, WebApplication1.FlightNamespace.FlightCalculatorSoap {
        
        public FlightCalculatorSoapClient() {
        }
        
        public FlightCalculatorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FlightCalculatorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlightCalculatorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlightCalculatorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.FlightNamespace.GetFligtsResponse WebApplication1.FlightNamespace.FlightCalculatorSoap.GetFligts(WebApplication1.FlightNamespace.GetFligtsRequest request) {
            return base.Channel.GetFligts(request);
        }
        
        public WebApplication1.FlightNamespace.ArrayOfString GetFligts() {
            WebApplication1.FlightNamespace.GetFligtsRequest inValue = new WebApplication1.FlightNamespace.GetFligtsRequest();
            inValue.Body = new WebApplication1.FlightNamespace.GetFligtsRequestBody();
            WebApplication1.FlightNamespace.GetFligtsResponse retVal = ((WebApplication1.FlightNamespace.FlightCalculatorSoap)(this)).GetFligts(inValue);
            return retVal.Body.GetFligtsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.FlightNamespace.GetFligtsResponse> WebApplication1.FlightNamespace.FlightCalculatorSoap.GetFligtsAsync(WebApplication1.FlightNamespace.GetFligtsRequest request) {
            return base.Channel.GetFligtsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.FlightNamespace.GetFligtsResponse> GetFligtsAsync() {
            WebApplication1.FlightNamespace.GetFligtsRequest inValue = new WebApplication1.FlightNamespace.GetFligtsRequest();
            inValue.Body = new WebApplication1.FlightNamespace.GetFligtsRequestBody();
            return ((WebApplication1.FlightNamespace.FlightCalculatorSoap)(this)).GetFligtsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.FlightNamespace.CreateNewFlightResponse WebApplication1.FlightNamespace.FlightCalculatorSoap.CreateNewFlight(WebApplication1.FlightNamespace.CreateNewFlightRequest request) {
            return base.Channel.CreateNewFlight(request);
        }
        
        public bool CreateNewFlight(string name, string from, string to) {
            WebApplication1.FlightNamespace.CreateNewFlightRequest inValue = new WebApplication1.FlightNamespace.CreateNewFlightRequest();
            inValue.Body = new WebApplication1.FlightNamespace.CreateNewFlightRequestBody();
            inValue.Body.name = name;
            inValue.Body.from = from;
            inValue.Body.to = to;
            WebApplication1.FlightNamespace.CreateNewFlightResponse retVal = ((WebApplication1.FlightNamespace.FlightCalculatorSoap)(this)).CreateNewFlight(inValue);
            return retVal.Body.CreateNewFlightResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.FlightNamespace.CreateNewFlightResponse> WebApplication1.FlightNamespace.FlightCalculatorSoap.CreateNewFlightAsync(WebApplication1.FlightNamespace.CreateNewFlightRequest request) {
            return base.Channel.CreateNewFlightAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.FlightNamespace.CreateNewFlightResponse> CreateNewFlightAsync(string name, string from, string to) {
            WebApplication1.FlightNamespace.CreateNewFlightRequest inValue = new WebApplication1.FlightNamespace.CreateNewFlightRequest();
            inValue.Body = new WebApplication1.FlightNamespace.CreateNewFlightRequestBody();
            inValue.Body.name = name;
            inValue.Body.from = from;
            inValue.Body.to = to;
            return ((WebApplication1.FlightNamespace.FlightCalculatorSoap)(this)).CreateNewFlightAsync(inValue);
        }
    }
}
